apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyanalyze
spec:
  replicas: 2
  selector:
    matchLabels:
      app: surveyanalyze
  template:
    metadata:
      labels:
        app: surveyanalyze
    spec:
      containers:
        - name: surveyanalyze
          image: hamgeonwook/surveyanalyze:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: surveyanalyze-service
spec:
  ports:
    - port: 8084
      targetPort: 8080
      protocol: TCP
  selector:
    app: surveyanalyze