FROM openjdk:11

WORKDIR /usr/src/app

COPY ./build/libs/surveydocument-0.0.1-SNAPSHOT.jar ./build/libs/surveydocument-0.0.1-SNAPSHOT.jar

EXPOSE 28080

CMD ["java","-jar","./build/libs/surveydocument-0.0.1-SNAPSHOT.jar"]
